apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bokeh
spec:
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        run: bokeh
    spec:
      containers:
      - name: bokeh
        image: gcr.io/dashapp-218819/dashboard-test@sha256:a07dcb8039d3cc94fbd2e268a129431f14acb2f79182c48560af725baf86b53f
        ports:
        - containerPort: 5006
        env:
        - name: GOOGLE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: project-id
              key: project-id
        - name: DASHBOARD_TEST_DOMAIN
          valueFrom:
            secretKeyRef:
              name: domain
              key: domain
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: service-account-key
              key: service-account-key

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: bokeh
  name: bokeh
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5006
    nodePort: 30033  # Arbitrary port for easy future reference
  selector:
    run: bokeh
  type: NodePort
